### ISSUE TITLE
bootstrap.min.js incorrectly sourced

### ISSUE THREAD

**Issue by Sqash** [lindsaybangs/lindsaybangs-version2#6]
Where every page loads bootstrap's js, the link is incorrect. Possibly originating as a typo in a template file.

`<script ... src="../js/bootstrap.min.js">` should read `<script ... src="../bootstrap-3.3.4/js/bootstrap.min.js">` I believe.

**Comment by lindsaybangs** [comment]
Made this change on local and sync'd. I'd still like to change these src's to maxcdns?
